version: "3.9"

services:
  db:
    container_name: check-in-app-database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: check-in-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default

  backend:
    container_name: check-in-app-backend
    image: check-in-app/backend:latest
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default

  frontend:
    container_name: check-in-app-frontend
    image: check-in-app/frontend:latest
    build: ./frontend
    ports:
      - "3001:3001"

networks:
  default:
